name: Build

on:
  workflow_call:
    inputs:
      ref:
        type: string
      runs-on:
        type: string
        default: 'ubuntu-latest'
      python-version:
        type: string
        default: '3.12'
      upload-documentation-artifacts:
        type: boolean
        default: false
      upload-build-artifacts:
        type: boolean
        default: false

jobs:
  build:
    name: ${{ inputs.runs-on }} python-${{ inputs.python-version }}
    runs-on: ${{ inputs.runs-on }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install packages
      run: pip install .

    - name: Run tests
      run: python -m unittest discover -v

    - name: Build documentation
      run: |-
        mkdir html
        git fetch --all
        python -I -m sphinx_multiversion -W docs html
        cp assets/gh-pages-redirect.html html/index.html

    - name: Upload documentation artifacts
      if: inputs.upload-documentation-artifacts
      uses: actions/upload-pages-artifact@v4
      with:
        path: html/

    - name: Install pypa/build
      run: pip install build

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Upload build artifacts
      if: inputs.upload-build-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
